// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOEE10QCaAiYHHtWt2iVKOLohPUEAKW00',
    appId: '1:437111373823:web:99af88adb4c87035f771ca',
    messagingSenderId: '437111373823',
    projectId: 'litlore-62236',
    authDomain: 'litlore-62236.firebaseapp.com',
    storageBucket: 'litlore-62236.firebasestorage.app',
    measurementId: 'G-8D75XEH8LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdEEDS7OjYRMHqCVgJIWFzQook4jmzCuM',
    appId: '1:437111373823:android:d216a6b9322dcec1f771ca',
    messagingSenderId: '437111373823',
    projectId: 'litlore-62236',
    storageBucket: 'litlore-62236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOzYZvV6l7dujCx6tpeSwbw3uDk-DKerc',
    appId: '1:437111373823:ios:589f61733ab0b62ff771ca',
    messagingSenderId: '437111373823',
    projectId: 'litlore-62236',
    storageBucket: 'litlore-62236.firebasestorage.app',
    androidClientId: '437111373823-0oincm7o0k1afiabtr5lj70pbr4gi9og.apps.googleusercontent.com',
    iosClientId: '437111373823-kjv1ng3l8qfbu0su2pvoj5jbbjtasnu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.litlore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOzYZvV6l7dujCx6tpeSwbw3uDk-DKerc',
    appId: '1:437111373823:ios:589f61733ab0b62ff771ca',
    messagingSenderId: '437111373823',
    projectId: 'litlore-62236',
    storageBucket: 'litlore-62236.firebasestorage.app',
    androidClientId: '437111373823-0oincm7o0k1afiabtr5lj70pbr4gi9og.apps.googleusercontent.com',
    iosClientId: '437111373823-kjv1ng3l8qfbu0su2pvoj5jbbjtasnu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.litlore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOEE10QCaAiYHHtWt2iVKOLohPUEAKW00',
    appId: '1:437111373823:web:bf7aa73af81a89a7f771ca',
    messagingSenderId: '437111373823',
    projectId: 'litlore-62236',
    authDomain: 'litlore-62236.firebaseapp.com',
    storageBucket: 'litlore-62236.firebasestorage.app',
    measurementId: 'G-Y2ZSLNFGJ0',
  );
}
